language: r

r_github_packages:
  - derivmkts

  secure: "FLT1g/8kqvkw+RLdzddR/pxPZagxDunGAo3FykEARW6sb/u27EsiERdGWjXC9sEmOor2NvPf02hBq0oWwtL6+3fS8/qGdTlbgDOgsmnX5xAVH3V4q4vqeNgUq+h26QinWrwfmvLmZlH5jQmyGIrWh9n7XTcxMuGpmxnxORQV30txwnFjXNyzUVrLjAgbudmNX6DwT65QMIz3EwSfYB1mbThDYWwvZT8oj+lk20KIH7ubJev54H2F5GjlwX4N0bUxaeVBSXGcA7BR4mvrJlQ6B6zL6qAG5inpVdv4+KZLzuWKsJsBnkWolVvOPeMI4mSj9l+akbUy7R4gTgzIKaB+IJ/mmGT8urtgI50yJsvfBeBP+QewtJ71RfRC24ftazErl5ROgr9w5SdeclkoxZRAFeVbxtj3hjRjUAULTBE1DkJBzrafyiWj6AqeZ5AJ+BWdZ6VIvzUzRS/gTN+mx+A4aSA8OUTzHdFHAyeFXk803k1n+8+VfLU/d0kDogkTVQhoZYt16iAagpAVJUR/jMO6snR8Uls6ld9SkOuG/iJgf0Kg8T2n+ZuF0ZOrPoOoXF6qZkymPgnD8KtoMjmR9PBnPRj96sEvc5p7dSgaowFGXiiYYRieuu65yEsWyurHJ/Tb50XF6IgsJOZs/nEtnZQX0/41OSLsN6BX+JYIWDl0FrI="

warnings_are_errors: true

sudo: required

after_success: R -e 'rmarkdown::render("README.Rmd")'
